apiVersion: "v1"

kind: "Pod"

metadata:
  name: "healthcheck-pod"
  labels:
    app: "healthcheck"

spec:
  containers:
  - name: "healthcheck-container"
    image: akshitgrover/healthcheck-example
    env:
      - name: "PORT"
        value: "3000"
    ports:
      - containerPort: 3000
    livenessProbe:
      httpGet:
        path: "/"
        port: 3000
      initialDelaySeconds: 11
      periodSeconds: 16
