apiVersion: "v1"

kind: "Service"

metadata:
  name: "healthcheck-example"

spec:
  selector:
    app: "healthcheck"

  type: "NodePort"
  
  ports:
    - targetPort: 3000
      nodePort: 30006
      port: 3000