apiVersion: v1

kind: Service

metadata:
  name: healthcheck-service

spec:
  
  selector:
    app: healthcheck
  
  type: NodePort

  ports:
  - targetPort: app-port
    port: 3000
    nodePort: 30006