apiVersion: v1

kind: Pod

metadata:
  name: healthcheck-pod
  labels:
    app: healthcheck

spec:
  containers:
  - name: healthcheck-container
    image: akshitgrover/healthcheck-example-curl
    ports:
    - name: app-port
      containerPort: 3000
      hostPort: 3000
    livenessProbe:
      exec:
        command: ["curl", "localhost:3000"]
      initialDelaySeconds: 11
      timeoutSeconds: 7
      periodSeconds: 7