apiVersion: apps/v1

kind: Deployment

metadata:
  name: helloworldsecret-deployment

spec:
  replicas: 3
  
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: ["helloworldsecret-app, "helloworld-app"]

  template:
    metadata:
      labels:
        app: helloworldsecret-app-vol
        
    spec:

      containers:
      - name: helloworldsecret-container
        image: akshitgrover/helloworldsecret-app
        ports:
        - name: app-port
          containerPort: 3000
        volumeMounts:
        - name: secretvolume
          mountPath: /var/secrets
          readOnly: true

      volumes:
      - name: secretvolume
        secret:
          secretName: helloworld-secret
          items:
          - key: content
            path: helloworldSecret/content
            mode: 256
    
