apiVersion: v1

kind: Pod

metadata:
  name: helloworldsecret-pod
  labels:
    app: helloworldsecret-app

spec:
  containers:
  - name: helloworldsecret-container
    image: akshitgrover/helloworldsecret-app
    ports:
    - name: app-port
      containerPort: 3000
    env:
    - name: HELLOWORLD_SECRET
      valueFrom:
        secretKeyRef:
          name: helloworld-secret
          key: content