apiVersion: v1

kind: Service

metadata:
  name: helloworldsecret-service

spec:
  type: NodePort

  selector:
    app: helloworldsecret-app

  ports:
  - targetPort: app-port
    port: 3000
    nodePort: 30006
    protocol: TCP